#
# Copyright (c) 2016 - 2020 Itspire.
# This software is licensed under the BSD-3-Clause license. (see LICENSE.md for full license)
# All rights reserved.
#
variables:
  PHP_IMAGE: $CI_REGISTRY/devops/docker-webservers/php-fpm-dev:4.1.1
  COMPOSER_IMAGE: $CI_REGISTRY/itspire-devops/webservers/composer-ci:3.0.2

default:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - docker-build

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - build
    - vendor

stages:
  - prepare
  - deps
  - analyse
  - test
  - artifacts

prepare:
  stage: prepare
  script:
    - mkdir -p build/coverage build/logs
    - rm -rf build/logs/*
    - rm -rf build/coverage/*

deps:
  stage: deps
  script:
    - >
      docker run \
          --rm \
          -v $(pwd):/project \
          -w /project \
          -e DEV_UID=$(id -u) \
          -e DEV_GID=$(id -g) \
          $COMPOSER_IMAGE install --prefer-dist
    - >
      docker run \
          --rm \
          -v $(pwd):/project \
          -w /project \
          -e DEV_UID=$(id -u) \
          -e DEV_GID=$(id -g) \
          $COMPOSER_IMAGE exec -vv -- simple-phpunit install

analyse:
  stage: analyse
  script:
    - >
      docker run \
          --rm \
          -v $(pwd):/project \
          -w /project \
          -e DEV_UID=$(id -u) \
          -e DEV_GID=$(id -g) \
          $PHP_IMAGE -l src/main/php src/test/php
    - >
      docker run \
          --rm \
          -v $(pwd):/project \
          -w /project \
          -e DEV_UID=$(id -u) \
          -e DEV_GID=$(id -g) \
          $PHP_IMAGE vendor/bin/phpcs \
              --report=full \
              --report-checkstyle=build/logs/checkstyle.xml \
              --standard=PSR12 \
              --extensions=php \
              --ignore=bootstrap.php \
              src/main/php src/test/php

test:
  stage: test
  script:
    - >
      docker run \
          --rm \
          -v $(pwd):/project \
          -w /project \
          -e DEV_UID=$(id -u) \
          -e DEV_GID=$(id -g) \
          $PHP_IMAGE vendor/bin/simple-phpunit

artifacts:
  stage: artifacts
  script:
    - echo "Generating artifacts..."
  artifacts:
    paths:
      - build
